---

- name: Deploy Xray Servers
  hosts: matryoshka
  remote_user: root
  gather_facts: true
  roles:
    - { role: enroll-system }
    - { role: install-docker }
    - { role: enable-bbr }
    - { role: configure-xray }

- name: Deploy Xray Pooler
  hosts: entry
  remote_user: root
  gather_facts: true
  roles:
    - { role: configure-puller }
