---

- name: Deploy Xray Servers
  hosts: servers
  remote_user: root
  gather_facts: true
  roles:
    - { role: enroll-system }
    - { role: install-docker }
    - { role: enable-bbr }
    - { role: configure-xray }
